# This file defines parameters used in TRESC and vis2c
# These parameters DO NOT affect electronic-structure calculations

# structured grid for `tshell -cub1c/-cub2c`
# rgrid=0.1 for high precision, rgrid=0.2 for medium precision
rgrid=0.15;   # grid spacing in REAL space /A.U.
# mgrid has a very wide range; please be patient and keep trying
# DO NOT use pro1c when dealing with core orbits
mgrid=0.3;    # grid spacing in MOMENTUM space /A.U.
edge=auto;    # edge distance in REAL space /A.U. set `auto` for convenience
sigma=auto;   # sigma coefficient in MOMENTUM space, set `auto` for convenience

# unstructured grid for `tshell -mog2c`, non-existent parameters are set to 0
mogtype=e    # =E/e: grid points defined by element; =I/i: by atom index
# for mogtype=E/e, use the tag nr[i]:
nr[1]=35, nl[1]=230;           # H
nr[2]=35, nl[2]=230;           # He
nr[3]=65, nl[3]=590;           # Li
nr[4]=65, nl[4]=590;           # Be
nr[5]=65, nl[5]=590;           # B
nr[6]=65, nl[6]=590;           # C
nr[7]=65, nl[7]=590;           # N
nr[8]=65, nl[8]=590;           # O
nr[9]=65, nl[9]=590;           # F
nr[10]=65, nl[10]=590;           # Ne
nr[11]=80, nl[11]=590;           # Na
nr[12]=80, nl[12]=590;           # Mg
nr[13]=80, nl[13]=590;           # Al
nr[14]=80, nl[14]=590;           # Si
nr[15]=80, nl[15]=590;           # P
nr[16]=80, nl[16]=590;           # S
nr[17]=80, nl[17]=590;           # Cl
nr[18]=80, nl[18]=590;           # Ar
nr[19]=100, nl[19]=590;           # K
nr[20]=100, nl[20]=590;           # Ca
nr[21]=100, nl[21]=590;           # Sc
nr[22]=100, nl[22]=590;           # Ti
nr[23]=100, nl[23]=590;           # V
nr[24]=100, nl[24]=590;           # Cr
nr[25]=100, nl[25]=590;           # Mn
nr[26]=100, nl[26]=590;           # Fe
nr[27]=100, nl[27]=590;           # Co
nr[28]=100, nl[28]=590;           # Ni
nr[29]=100, nl[29]=590;           # Cu
nr[30]=100, nl[30]=590;           # Zn

# for mogtype=I/i, use the tag nr{i}:
nr{1}=65, nl{1}=590;
nr{2}=65, nl{2}=590;
nr{3}=100, nl{3}=590;
